services:
  wedding:
    build:
      context: .
      dockerfile: Dockerfile
    image: wedding:latest
    container_name: wedding
    restart: always
    volumes:
      - '.:/usr/src/app'
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
